type UserProfile {
    id: ID!
    user_id: ID!
    nama_lengkap: String!
    nrp: String
    alamat: String
    foto: String
    bagian_id: ID
    level_id: ID
    status_id: ID
}

input CreateUsersProfile {
    user_id: ID!
    nama_lengkap: String!
    nrp: String
    alamat: String
    foto: String
    bagian_id: ID
    level_id: ID
    status_id: ID
}

input UpdateUsersProfile {
    id: ID!
    user_id: ID!
    nama_lengkap: String!
    nrp: String
    alamat: String
    foto: String
    bagian_id: ID
    level_id: ID
    status_id: ID
}

extend type Query {
    allUsersProfile: [UserProfile!]!
        @all(model: "App\\Models\\ModelUsersProfile")
        @softDeletes

    UsersProfile(id: ID! @eq(key: "id")): UserProfile
        @find(model: "App\\Models\\ModelUsersProfile")
        @softDeletes

    UsersProfileByNama(
        nama_lengkap: String! @where(operator: "like", key: "nama_lengkap")
    ): [UserProfile!]!
        @all(model: "App\\Models\\ModelUsersProfile")
        @softDeletes
}

extend type Mutation {
    createUsersProfileInput(input: CreateUsersProfile @spread): UserProfile
        @create(model: "App\\Models\\ModelUsersProfile")

    updateUsersProfileInput(input: UpdateUsersProfile @spread): UserProfile
        @update(model: "App\\Models\\ModelUsersProfile")

    deleteUsersProfile(id: ID! @eq(key: "id")): UserProfile
        @delete(model: "App\\Models\\ModelUsersProfile")

    restoreUsersProfile(id: ID! @eq(key: "id")): UserProfile
        @field(
            resolver: "App\\GraphQL\\Mutations\\UsersProfile\\usersProfile@restore"
        )

    forceDeleteUsersProfile(id: ID! @eq(key: "id")): UserProfile
        @field(
            resolver: "App\\GraphQL\\Mutations\\UsersProfile\\usersProfile@forceDelete"
        )
}
