type UserProfile {
    id: ID!
    user_id: ID!
    nama_lengkap: String!
    nrp: String
    alamat: String
    foto: String
    bagian_id: ID
    level_id: ID
    status_id: ID

    bagian: Bagian @belongsTo
    level: Level @belongsTo
    status: Status @belongsTo

    created_at: DateTime
    updated_at: DateTime
    deleted_at: DateTime
}

input CreateUsersProfile {
    user_id: ID!
    nama_lengkap: String!
    nrp: String
    alamat: String
    foto: String
    bagian_id: ID
    level_id: ID
    status_id: ID
}

input UpdateUsersProfile {
    id: ID!
    user_id: ID!
    nama_lengkap: String!
    nrp: String
    alamat: String
    foto: String
    bagian_id: ID
    level_id: ID
    status_id: ID
}

extend type Query {
    allUserProfile: [UserProfile!]!
        @all(model: "App\\Models\\ModelUsersProfile")
        @softDeletes

    UserProfile(id: ID! @eq(key: "id")): UserProfile
        @find(model: "App\\Models\\ModelUsersProfile")
        @softDeletes

    UserProfileByNama(
        nama_lengkap: String! @where(operator: "like", key: "nama_lengkap")
    ): [UserProfile!]!
        @all(model: "App\\Models\\ModelUsersProfile")
        @softDeletes
}

extend type Mutation {
    createUserProfileInput(input: CreateUsersProfile @spread): UserProfile
        @create(model: "App\\Models\\ModelUsersProfile")

    updateUserProfileInput(input: UpdateUsersProfile @spread): UserProfile
        @update(model: "App\\Models\\ModelUsersProfile")

    deleteUserProfile(id: ID! @eq(key: "id")): UserProfile
        @delete(model: "App\\Models\\ModelUsersProfile")

    restoreUserProfile(id: ID! @eq(key: "id")): UserProfile
        @field(
            resolver: "App\\GraphQL\\Mutations\\UsersProfile\\usersProfile@restore"
        )

    forceDeleteUserProfile(id: ID! @eq(key: "id")): UserProfile
        @field(
            resolver: "App\\GraphQL\\Mutations\\UsersProfile\\usersProfile@forceDelete"
        )
}
