type JamKerja {
    id: ID!
    users_profile_id: ID!
    no_wbs: String
    kode_proyek: String
    proyek_id: ID!
    aktivitas_id: ID!
    tanggal: Date!
    jumlah_jam: Float!
    keterangan: String
    status_id: ID
    mode_id: ID
    created_at: DateTime
    updated_at: DateTime
    deleted_at: DateTime
    users_profile: UserProfile @belongsTo
    proyek: Proyek @belongsTo
    aktivitas: Aktivitas @belongsTo
    status: StatusJamKerja @belongsTo
    mode: ModeJamKerja @belongsTo
}

input CreateJamKerjaInput {
    users_profile_id: ID!
    no_wbs: String
    kode_proyek: String
    proyek_id: ID!
    aktivitas_id: ID!
    tanggal: Date!
    jumlah_jam: Float!
    keterangan: String
    status_id: ID
    mode_id: ID
}

input UpdateJamKerjaInput {
    id: ID!
    users_profile_id: ID
    no_wbs: String
    kode_proyek: String
    proyek_id: ID
    aktivitas_id: ID
    tanggal: Date
    jumlah_jam: Float
    keterangan: String
    status_id: ID
    mode_id: ID
}

extend type Query {
    allJamKerja: [JamKerja!]! @all(model: "App\\Models\\ModelJamKerja") @softDeletes
    JamKerja(id: ID! @eq(key: "id")): JamKerja @find(model: "App\\Models\\ModelJamKerja") @softDeletes
}

extend type Mutation {
    createJamKerja(input: CreateJamKerjaInput @spread): JamKerja @create(model: "App\\Models\\ModelJamKerja")
    updateJamKerja(input: UpdateJamKerjaInput @spread): JamKerja @update(model: "App\\Models\\ModelJamKerja")
    deleteJamKerja(id: ID! @eq(key: "id")): JamKerja @delete(model: "App\\Models\\ModelJamKerja")
    restoreJamKerja(id: ID! @eq(key: "id")): JamKerja @field(resolver: "App\\GraphQL\\Mutations\\JamKerja\\JamKerjaMutations@restore")
    forceDeleteJamKerja(id: ID! @eq(key: "id")): JamKerja @field(resolver: "App\\GraphQL\\Mutations\\JamKerja\\JamKerjaMutations@forceDelete")
}