type Pesan {
    id: ID!
    pengirim: String!
    penerima: String!
    isi: String!
    parent_id: ID
    tgl_pesan: DateTime!
    jenis_id: ID
    created_at: DateTime
    updated_at: DateTime
    deleted_at: DateTime
    jenis: Jenis @belongsTo
    parent: Pesan @belongsTo
    replies: [Pesan!] @hasMany
}

input CreatePesanInput {
    pengirim: String!
    penerima: String!
    isi: String!
    parent_id: ID
    tgl_pesan: DateTime!
    jenis_id: ID
}

input UpdatePesanInput {
    id: ID!
    pengirim: String
    penerima: String
    isi: String
    parent_id: ID
    tgl_pesan: DateTime
    jenis_id: ID
}

extend type Query {
    allPesan: [Pesan!]! @all(model: "App\\Models\\ModelPesan") @softDeletes
    Pesan(id: ID! @eq(key: "id")): Pesan
        @find(model: "App\\Models\\ModelPesan")
        @softDeletes
}

extend type Mutation {
    createPesan(input: CreatePesanInput @spread): Pesan
        @create(model: "App\\Models\\ModelPesan")
    updatePesan(input: UpdatePesanInput @spread): Pesan
        @update(model: "App\\Models\\ModelPesan")
    deletePesan(id: ID! @eq(key: "id")): Pesan
        @delete(model: "App\\Models\\ModelPesan")
    restorePesan(id: ID! @eq(key: "id")): Pesan
        @field(
            resolver: "App\\GraphQL\\Mutations\\Pesan\\PesanMutations@restore"
        )
    forceDeletePesan(id: ID! @eq(key: "id")): Pesan
        @field(
            resolver: "App\\GraphQL\\Mutations\\Pesan\\PesanMutations@forceDelete"
        )
}
