type Status{
    id: ID!
    nama: String!
    created_at: DateTime
    updated_at: DateTime
    deleted_at: DateTime
}

extend type Query {
    allStatus: [Status!]! @all(model: "App\\Models\\ModelStatus") @softDeletes

    Status(id: ID! @eq(key: "id")): Status
        @find(model: "App\\Models\\ModelStatus")
        @softDeletes

    StatusByNama(nama: String! @where(operator: "like", key: "nama")): [Status!]!
        @all(model: "App\\Models\\ModelStatus")
        @softDeletes
}

extend type Mutation {
    createStatusInput(nama: String!): Status
        @create(model: "App\\Models\\ModelStatus")

    updateStatusInput(id: ID!, nama: String!): Status
        @update(model: "App\\Models\\ModelStatus")

    deleteStatus(id: ID! @eq(key: "id")): Status
        @delete(model: "App\\Models\\ModelStatus")

    restoreStatus(id: ID! @eq(key: "id")): Status
        @field(
            resolver: "App\\GraphQL\\Mutations\\Status\\statusMutations@restore"
        )

    forceDeleteStatus(id: ID! @eq(key: "id")): Status
        @field(
            resolver:
                "App\\GraphQL\\Mutations\\Status\\statusMutations@forceDelete"
        )
}
