type Bagian {
    id: ID!
    nama: String!
    created_at: DateTime
    updated_at: DateTime
}

input CreateBagianInput {
    nama: String!
}

input UpdateBagianInput {
    id: ID!
    nama: String
}

extend type Query {
    allBagian: [Bagian!]! @all(model: "App\\Models\\ModelBagian")

    bagian(id: ID! @eq(key: "id")): Bagian
        @find(model: "App\\Models\\ModelBagian")

    BagianByNama(
        nama: String! @where(operator: "like", key: "nama")
    ): [Bagian!]! @all(model: "App\\Models\\ModelBagian")
}

extend type Mutation {
    createBagianInput(input: CreateBagianInput @spread): Bagian
        @create(model: "App\\Models\\ModelBagian")

    updateBagianInput(input: UpdateBagianInput @spread): Bagian
        @update(model: "App\\Models\\ModelBagian")

    deleteBagian(id: ID! @eq(key: "id")): Bagian
        @delete(model: "App\\Models\\ModelBagian")
}
