type User {
    id: ID!
    name: String!
    email: String!
    email_verified_at: DateTime
    created_at: DateTime
    updated_at: DateTime
    deleted_at: DateTime
    profile: UserProfile @hasOne
}

input CreateUserInput {
    name: String!
    email: String!
    password: String
}

input UpdateUserInput {
    id: ID!
    name: String
    email: String
}

extend type Query {
    allUser: [User!]! @all(model: "App\\Models\\User") @softDeletes
    User(id: ID! @eq(key: "id")): User
        @find(model: "App\\Models\\User")
        @softDeletes
}

extend type Mutation {
    createUser(input: CreateUserInput @spread): User
        @create(model: "App\\Models\\User")
    updateUser(input: UpdateUserInput @spread): User
        @update(model: "App\\Models\\User")
    deleteUser(id: ID! @eq(key: "id")): User @delete(model: "App\\Models\\User")
    restoreUser(id: ID! @eq(key: "id")): User
        @field(resolver: "App\\GraphQL\\Mutations\\User\\UserMutations@restore")
    forceDeleteUser(id: ID! @eq(key: "id")): User
        @field(
            resolver: "App\\GraphQL\\Mutations\\User\\UserMutations@forceDelete"
        )
}
